name: libertine
version: 1.7.1+17.04.20170331-0ubuntu1
summary: Libertine suite
description: |
    Suite for maintaining deb-based applications in a non-deb environment
confinement: strict
grade: devel

slots:
  libertined:
    interface: dbus
    name: com.canonical.libertine.Service
    bus: session

plugs:
  libertined-client:
    interface: dbus
    name: com.canonical.libertine.Service
    bus: session

apps:
  libertined:
    command: usr/bin/snap-runner.wrapper libertined
    plugs:
      - lxd
      - network
      - network-bind
    slots:
      - libertined
    # daemon: simple # Waiting on LP:1613420
  launch:
    command: usr/bin/snap-runner.wrapper libertine-launch
    aliases:
      - libertine-launch
    plugs:
      - lxd
      - network
      - network-bind
      - home
      - x11
      - unity7
      - opengl
      - pulseaudio
      - alsa
      - libertined-client
  container-manager:
    command: usr/bin/snap-runner.wrapper libertine-container-manager
    aliases:
      - libertine-container-manager
    plugs:
      - lxd
      - network
      - libertined-client
  manager-app:
    command: usr/bin/snap-runner.wrapper libertine-manager-app
    # desktop command currently being labeled unknown by app store, restore with snapcraft 2.26 release
    # desktop: usr/share/applications/libertine-manager-app.desktop
    aliases:
      - libertine-manager-app

  # For debugging purposes
  bash:
    command: usr/bin/snap-runner.wrapper bash
    plugs:
      - libertined-client

parts:
  libertine-source:
    plugin: libertine
    source: .
    after:
      - desktop-qt5
  libertine-deps:
    plugin: libertine-deps
  env:
    plugin: dump
    source: snap/
    organize:
      snap-runner.wrapper: usr/bin/snap-runner.wrapper
