name: libertine
version: 1.5.1+17.04.20170118-0ubuntu1
summary: Libertine suite
description: |
    Suite for maintaining deb-based applications in a non-deb environment
confinement: devmode # TODO: update to 'strict'
grade: devel

apps:
  launch:
    command: usr/bin/snap-runner.wrapper libertine-launch
    aliases:
      - libertine-launch
    plugs:
      - lxd
      - network
      - network-bind
      - home
      - mir
      - x11
      - unity7
      - opengl
      - pulseaudio
      - alsa
  container-manager:
    command: usr/bin/snap-runner.wrapper libertine-container-manager
    aliases:
      - libertine-container-manager
    plugs:
      - lxd
      - network
  manager-app:
    command: usr/bin/snap-runner.wrapper libertine-manager-app
    # desktop command currently being labeled unknown by app store, restore with snapcraft 2.26 release
    # desktop: usr/share/applications/libertine-manager-app.desktop
    aliases:
      - libertine-manager-app

  # For debugging purposes
  bash:
    command: usr/bin/snap-runner.wrapper bash

parts:
  libertine-source:
    plugin: libertine
    source: .
    after:
      - desktop-qt5
  libertine-deps:
    plugin: libertine-deps
  env:
    plugin: dump
    organize:
      data/snap-runner.wrapper: usr/bin/snap-runner.wrapper
